//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYBUSINESS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinalProduction
    {
        public decimal Id { get; set; }
        public System.DateTime Date { get; set; }
        public string ProductName { get; set; }
        public string Unit { get; set; }
        public int QuantityToProduce { get; set; }
        public Nullable<decimal> ProductId { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
