
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MYBUSINESS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Location
{

    public decimal Id { get; set; }

    public string Name { get; set; }

    public string Remarks { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public Nullable<System.DateTime> UpdateDate { get; set; }

    public string bizId { get; set; }

    public Nullable<int> StoreId { get; set; }



    public virtual BusinessInfo BusinessInfo { get; set; }

}

}
