//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYBUSINESS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItemPProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderItemPProduct()
        {
            this.StoreOrderReceiptPPs = new HashSet<StoreOrderReceiptPP>();
        }
    
        public int Id { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<decimal> ProductId { get; set; }
        public Nullable<decimal> Quantity { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual OrderPProduct OrderPProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StoreOrderReceiptPP> StoreOrderReceiptPPs { get; set; }
    }
}
