
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MYBUSINESS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PackagingColored
{

    public int Id { get; set; }

    public string Remarks { get; set; }

    public Nullable<bool> Saleable { get; set; }

    public Nullable<bool> Purchasable { get; set; }

    public Nullable<bool> Manufacturable { get; set; }

    public Nullable<int> ShelfLife { get; set; }

    public string TimeUnit { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public Nullable<System.DateTime> UpdateDate { get; set; }

    public string ProductionProcessCateogry { get; set; }

    public string ProductionProcessDescription { get; set; }

    public string ProductName { get; set; }

    public Nullable<decimal> ProductId { get; set; }

    public string Unit { get; set; }

}

}
