//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYBUSINESS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaperColor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaperColor()
        {
            this.PPColorReceipts = new HashSet<PPColorReceipt>();
            this.CPReceipts = new HashSet<CPReceipt>();
            this.ProductStockDetails = new HashSet<ProductStockDetail>();
            this.BOXProductions = new HashSet<BOXProduction>();
        }
    
        public int Id { get; set; }
        public string Color { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> ProductId { get; set; }
        public Nullable<int> PackagingProductionId { get; set; }
        public string ColorCode { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual PackagingProduction PackagingProduction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PPColorReceipt> PPColorReceipts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CPReceipt> CPReceipts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductStockDetail> ProductStockDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOXProduction> BOXProductions { get; set; }
    }
}
