//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYBUSINESS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaperColor
    {
        public int Id { get; set; }
        public string Color { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> ProductId { get; set; }
        public Nullable<int> PackagingProductionId { get; set; }
    
        public virtual PackagingProduction PackagingProduction { get; set; }
        public virtual Product Product { get; set; }
    }
}
