//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYBUSINESS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PPColorReceipt
    {
        public int Id { get; set; }
        public Nullable<int> PaperColorId { get; set; }
        public Nullable<decimal> PPSubItemId { get; set; }
        public Nullable<int> QuantityReceived { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public Nullable<int> PannerQty { get; set; }
        public Nullable<int> ToReceived { get; set; }
    
        public virtual PaperColor PaperColor { get; set; }
    }
}
