
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MYBUSINESS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PPReciverDetail
{

    public decimal Auto { get; set; }

    public string PPReciverId { get; set; }

    public Nullable<int> PPDReciverId { get; set; }

    public Nullable<decimal> ProductId { get; set; }

    public Nullable<decimal> OpeningStock { get; set; }

    public Nullable<int> Quantity { get; set; }

    public Nullable<decimal> PurchasePrice { get; set; }

    public Nullable<decimal> PerPack { get; set; }

    public Nullable<bool> IsPack { get; set; }

    public Nullable<bool> SaleType { get; set; }

    public string Remarks { get; set; }

    public Nullable<System.DateTime> ExpiryDate { get; set; }

    public Nullable<System.DateTime> PurchasingDate { get; set; }

    public string Unit { get; set; }

    public Nullable<decimal> QtyReceived { get; set; }

    public Nullable<bool> Validate { get; set; }



    public virtual PPReceiver PPReceiver { get; set; }

    public virtual Product Product { get; set; }

}

}
