//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYBUSINESS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PPSubItemProduction
    {
        public decimal Id { get; set; }
        public Nullable<decimal> ParentProductId { get; set; }
        public Nullable<decimal> ProductId { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<int> BOMId { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> AvailableInventory { get; set; }
        public Nullable<decimal> QuantityRequested { get; set; }
        public Nullable<decimal> QuantitytoPrepare { get; set; }
        public Nullable<byte> ProductType { get; set; }
        public Nullable<int> NewProductionId { get; set; }
        public Nullable<int> PostProductionId { get; set; }
        public Nullable<decimal> SubItemQty { get; set; }
    
        public virtual PPNewProduction PPNewProduction { get; set; }
        public virtual Product Product { get; set; }
        public virtual PPPostProduction PPPostProduction { get; set; }
    }
}
