//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYBUSINESS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductType
    {
        public int Id { get; set; }
        public Nullable<decimal> ProductionQty { get; set; }
        public Nullable<int> BOMId { get; set; }
        public Nullable<decimal> ProductDetailId { get; set; }
    
        public virtual BOM BOM { get; set; }
    }
}
