
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MYBUSINESS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ProductionDetail
{

    public int Id { get; set; }

    public Nullable<int> ProdctuionId { get; set; }

    public Nullable<decimal> ProductId { get; set; }

    public string ShapeId { get; set; }

    public string ShapePrdnQty { get; set; }

    public string VarProd { get; set; }

    public string ExcessProd { get; set; }

    public string ByProd { get; set; }



    public virtual NewProduction NewProduction { get; set; }

    public virtual Product Product { get; set; }

}

}
