
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MYBUSINESS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ProductStockDetail
{

    public int Id { get; set; }

    public Nullable<int> PackagingProductionId { get; set; }

    public Nullable<decimal> ProductId { get; set; }

    public Nullable<int> PaperColorId { get; set; }

    public Nullable<int> Quantity { get; set; }

    public Nullable<System.DateTime> DateManufactured { get; set; }

    public Nullable<System.DateTime> DateExpiry { get; set; }



    public virtual PackagingProduction PackagingProduction { get; set; }

    public virtual PaperColor PaperColor { get; set; }

    public virtual Product Product { get; set; }

}

}
