
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MYBUSINESS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ProductionDetail1
{

    public int ProdctuionId { get; set; }

    public Nullable<decimal> ProductId { get; set; }

    public Nullable<decimal> ShapeId { get; set; }

    public Nullable<decimal> ShapePrdnQty { get; set; }

    public Nullable<decimal> VarProd { get; set; }

    public Nullable<decimal> ExcessProd { get; set; }

    public Nullable<decimal> ByProd { get; set; }

    public Nullable<decimal> Qty { get; set; }

}

}
