//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYBUSINESS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuantityToProduce
    {
        public int Id { get; set; }
        public Nullable<decimal> ProductionQty { get; set; }
        public Nullable<decimal> ProductDetailId { get; set; }
        public Nullable<decimal> ProductId { get; set; }
        public string Shape { get; set; }
        public Nullable<int> NewProductionId { get; set; }
        public Nullable<decimal> CalculatedWeight { get; set; }
        public Nullable<int> PostProductionId { get; set; }
        public Nullable<decimal> Weight { get; set; }
    
        public virtual PostProduction PostProduction { get; set; }
        public virtual Product Product { get; set; }
        public virtual ProductDetail ProductDetail { get; set; }
    }
}
