//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYBUSINESS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopManage
    {
        public string Id { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public int ShoreId { get; set; }
        public Nullable<byte> TransactionType { get; set; }
        public string Note { get; set; }
        public string CurrencyName { get; set; }
        public Nullable<int> JPYQuantity { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> VNDQuantity { get; set; }
        public Nullable<int> USDQuantity { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
